# Generated by Django 4.1.6 on 2023-02-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_credit', models.CharField(max_length=10)),
                ('acq_creidt', models.CharField(max_length=10)),
                ('rating_cnt', models.CharField(max_length=10)),
                ('r_scores', models.CharField(max_length=10)),
                ('r_scores_avg', models.CharField(max_length=10)),
                ('per_score', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Private',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=10)),
                ('class_num', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('div_class', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
    ]
